2014-09-03T10:03:43+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Please specify a shipping method.' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(303): Mage::throwException('Please specify ...')
#1 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(222): Mage_Sales_Model_Service_Quote->_validate()
#2 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(238): Mage_Sales_Model_Service_Quote->submitNominalItems()
#3 /var/www/magento/app/code/core/Mage/Checkout/Model/Type/Onepage.php(785): Mage_Sales_Model_Service_Quote->submitAll()
#4 /var/www/magento/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /var/www/magento/index.php(87): Mage::run('', 'store')
#11 {main}
2014-09-03T10:03:52+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Please specify a shipping method.' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(303): Mage::throwException('Please specify ...')
#1 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(222): Mage_Sales_Model_Service_Quote->_validate()
#2 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(238): Mage_Sales_Model_Service_Quote->submitNominalItems()
#3 /var/www/magento/app/code/core/Mage/Checkout/Model/Type/Onepage.php(785): Mage_Sales_Model_Service_Quote->submitAll()
#4 /var/www/magento/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /var/www/magento/index.php(87): Mage::run('', 'store')
#11 {main}
2014-09-03T10:04:04+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Please specify a shipping method.' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(303): Mage::throwException('Please specify ...')
#1 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(222): Mage_Sales_Model_Service_Quote->_validate()
#2 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(238): Mage_Sales_Model_Service_Quote->submitNominalItems()
#3 /var/www/magento/app/code/core/Mage/Checkout/Model/Type/Onepage.php(785): Mage_Sales_Model_Service_Quote->submitAll()
#4 /var/www/magento/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /var/www/magento/index.php(87): Mage::run('', 'store')
#11 {main}
2014-09-03T10:04:16+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Please specify a shipping method.' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(303): Mage::throwException('Please specify ...')
#1 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(222): Mage_Sales_Model_Service_Quote->_validate()
#2 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(238): Mage_Sales_Model_Service_Quote->submitNominalItems()
#3 /var/www/magento/app/code/core/Mage/Checkout/Model/Type/Onepage.php(785): Mage_Sales_Model_Service_Quote->submitAll()
#4 /var/www/magento/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /var/www/magento/index.php(87): Mage::run('', 'store')
#11 {main}
2014-09-03T10:04:23+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Please specify a shipping method.' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(303): Mage::throwException('Please specify ...')
#1 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(222): Mage_Sales_Model_Service_Quote->_validate()
#2 /var/www/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(238): Mage_Sales_Model_Service_Quote->submitNominalItems()
#3 /var/www/magento/app/code/core/Mage/Checkout/Model/Type/Onepage.php(785): Mage_Sales_Model_Service_Quote->submitAll()
#4 /var/www/magento/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /var/www/magento/index.php(87): Mage::run('', 'store')
#11 {main}
2014-09-04T07:25:40+00:00 ERR (3): 
exception 'Zend_Mail_Transport_Exception' with message 'Unable to send mail. ' in /var/www/magento/lib/Zend/Mail/Transport/Sendmail.php:137
Stack trace:
#0 /var/www/magento/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Sendmail->_sendMail()
#1 /var/www/magento/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#2 /var/www/magento/app/code/core/Mage/Core/Model/Email/Template.php(454): Zend_Mail->send()
#3 /var/www/magento/app/code/core/Mage/Core/Model/Email/Template.php(506): Mage_Core_Model_Email_Template->send('', 'Madison Island', Array)
#4 /var/www/magento/app/code/community/VladimirPopov/WebForms/Model/Results.php(126): Mage_Core_Model_Email_Template->sendTransactional('webforms_notifi...', Array, '', 'Madison Island', Array, '1')
#5 /var/www/magento/app/code/community/VladimirPopov/WebForms/Model/Webforms.php(320): VladimirPopov_WebForms_Model_Results->sendEmail()
#6 /var/www/magento/app/code/community/VladimirPopov/WebForms/controllers/IndexController.php(27): VladimirPopov_WebForms_Model_Webforms->savePostResult()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): VladimirPopov_WebForms_IndexController->iframeAction()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('iframe')
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#11 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /var/www/magento/index.php(87): Mage::run('', 'store')
#13 {main}
