<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Go to partner site'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <button type="button" class="button btn-cart" onclick="javascript:window.location.href='<?php
            echo Mage::helper('solvingmagento_affiliateproduct')->getRedirectUrl($_product);?>'; return false;">
            <span><span><?php echo $buttonTitle ?></span></span>
        </button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
