2014-09-19T09:48:24+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-19T09:48:40+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-19T09:57:35+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-19T09:58:39+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-19T10:00:45+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-19T11:57:30+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T07:02:01+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T07:08:18+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T07:20:09+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T07:25:28+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T08:10:13+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T10:50:11+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T11:15:50+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-22T11:17:15+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-22T11:55:58+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T11:56:23+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T11:56:48+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T11:57:10+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T11:57:57+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:01:33+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:01:59+00:00 ERR (3): 
exception 'Exception' with message 'Disallowed file type.' in /var/www/magento/lib/Varien/File/Uploader.php:254
Stack trace:
#0 /var/www/magento/lib/Varien/File/Uploader.php(180): Varien_File_Uploader->_validateFile()
#1 /var/www/magento/app/code/community/SSTech/Profileimage/Model/Profileimage.php(47): Varien_File_Uploader->save('/var/www/magent...', 'images.jpeg')
#2 /var/www/magento/app/code/community/SSTech/Profileimage/Model/Observer.php(11): SSTech_Profileimage_Model_Profileimage->saveProfileimageFile()
#3 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1338): SSTech_Profileimage_Model_Observer->saveCustomerProfileimage(Object(Varien_Event_Observer))
#4 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(SSTech_Profileimage_Model_Observer), 'saveCustomerPro...', Object(Varien_Event_Observer))
#5 /var/www/magento/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('customer_save_b...', Array)
#6 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('customer_save_b...', Array)
#7 /var/www/magento/app/code/core/Mage/Customer/Model/Customer.php(208): Mage_Core_Model_Abstract->_beforeSave()
#8 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(316): Mage_Customer_Model_Customer->_beforeSave()
#9 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#12 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#14 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 /var/www/magento/index.php(87): Mage::run('', 'store')
#16 {main}
2014-09-22T12:02:59+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:04:21+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:04:38+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:20:41+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:21:36+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:22:44+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:23:42+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:32:22+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:44:00+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:54:00+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T12:54:10+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T13:04:16+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-22T13:04:31+00:00 ERR (3): 
exception 'Exception' with message 'Disallowed file type.' in /var/www/magento/lib/Varien/File/Uploader.php:254
Stack trace:
#0 /var/www/magento/lib/Varien/File/Uploader.php(180): Varien_File_Uploader->_validateFile()
#1 /var/www/magento/app/code/community/SSTech/Profileimage/Model/Profileimage.php(47): Varien_File_Uploader->save('/var/www/magent...', 'images.jpeg')
#2 /var/www/magento/app/code/community/SSTech/Profileimage/Model/Observer.php(11): SSTech_Profileimage_Model_Profileimage->saveProfileimageFile()
#3 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1338): SSTech_Profileimage_Model_Observer->saveCustomerProfileimage(Object(Varien_Event_Observer))
#4 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(SSTech_Profileimage_Model_Observer), 'saveCustomerPro...', Object(Varien_Event_Observer))
#5 /var/www/magento/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('customer_save_b...', Array)
#6 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('customer_save_b...', Array)
#7 /var/www/magento/app/code/core/Mage/Customer/Model/Customer.php(208): Mage_Core_Model_Abstract->_beforeSave()
#8 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(316): Mage_Customer_Model_Customer->_beforeSave()
#9 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#12 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#14 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 /var/www/magento/index.php(87): Mage::run('', 'store')
#16 {main}
2014-09-23T05:50:54+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-23T06:22:07+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-23T09:10:04+00:00 ERR (3): 
exception 'Mage_Customer_Exception' with message 'Customer email is required' in /var/www/magento/app/Mage.php:580
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Customer/Model/Resource/Customer.php(76): Mage::exception('Mage_Customer', 'Customer email ...')
#1 /var/www/magento/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1122): Mage_Customer_Model_Resource_Customer->_beforeSave(Object(Mage_Customer_Model_Customer))
#2 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Customer_Model_Customer))
#3 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#4 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/magento/index.php(87): Mage::run('', 'store')
#10 {main}
2014-09-23T09:10:17+00:00 ERR (3): 
exception 'Mage_Customer_Exception' with message 'Customer email is required' in /var/www/magento/app/Mage.php:580
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Customer/Model/Resource/Customer.php(76): Mage::exception('Mage_Customer', 'Customer email ...')
#1 /var/www/magento/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1122): Mage_Customer_Model_Resource_Customer->_beforeSave(Object(Mage_Customer_Model_Customer))
#2 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Customer_Model_Customer))
#3 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#4 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/magento/index.php(87): Mage::run('', 'store')
#10 {main}
2014-09-23T09:10:38+00:00 ERR (3): 
exception 'Mage_Customer_Exception' with message 'Customer email is required' in /var/www/magento/app/Mage.php:580
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Customer/Model/Resource/Customer.php(76): Mage::exception('Mage_Customer', 'Customer email ...')
#1 /var/www/magento/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1122): Mage_Customer_Model_Resource_Customer->_beforeSave(Object(Mage_Customer_Model_Customer))
#2 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Customer_Model_Customer))
#3 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#4 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/magento/index.php(87): Mage::run('', 'store')
#10 {main}
2014-09-23T09:11:19+00:00 ERR (3): 
exception 'Mage_Customer_Exception' with message 'Customer email is required' in /var/www/magento/app/Mage.php:580
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Customer/Model/Resource/Customer.php(76): Mage::exception('Mage_Customer', 'Customer email ...')
#1 /var/www/magento/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1122): Mage_Customer_Model_Resource_Customer->_beforeSave(Object(Mage_Customer_Model_Customer))
#2 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Customer_Model_Customer))
#3 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#4 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/magento/index.php(87): Mage::run('', 'store')
#10 {main}
2014-09-23T09:12:55+00:00 ERR (3): 
exception 'Mage_Customer_Exception' with message 'Customer email is required' in /var/www/magento/app/Mage.php:580
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Customer/Model/Resource/Customer.php(76): Mage::exception('Mage_Customer', 'Customer email ...')
#1 /var/www/magento/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1122): Mage_Customer_Model_Resource_Customer->_beforeSave(Object(Mage_Customer_Model_Customer))
#2 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Customer_Model_Customer))
#3 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#4 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/magento/index.php(87): Mage::run('', 'store')
#10 {main}
2014-09-23T09:13:04+00:00 ERR (3): 
exception 'Mage_Customer_Exception' with message 'Customer email is required' in /var/www/magento/app/Mage.php:580
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Customer/Model/Resource/Customer.php(76): Mage::exception('Mage_Customer', 'Customer email ...')
#1 /var/www/magento/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1122): Mage_Customer_Model_Resource_Customer->_beforeSave(Object(Mage_Customer_Model_Customer))
#2 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Customer_Model_Customer))
#3 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#4 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/magento/index.php(87): Mage::run('', 'store')
#10 {main}
2014-09-23T10:44:19+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-23T10:44:23+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-23T10:44:24+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-23T10:44:25+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-23T10:44:25+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-23T10:44:25+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-23T10:44:26+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-23T10:51:20+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-23T11:42:10+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-23T11:49:49+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-23T11:51:09+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: Mage_Profileimage_Block_Widget_Upload' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('profileimage/wi...', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('profileimage/wi...', 'profileimage.fi...')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('profileimage/wi...', 'profileimage.fi...')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(256): Mage_Core_Controller_Varien_Action->loadLayout()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->createAction()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('create')
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#14 /var/www/magento/index.php(87): Mage::run('', 'store')
#15 {main}
2014-09-23T13:16:20+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T07:42:52+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T07:44:53+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T07:46:59+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T07:56:05+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T07:58:06+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T08:00:48+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T08:01:05+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T10:35:59+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T10:47:02+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T10:47:10+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T11:57:18+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T11:59:07+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T12:00:01+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T12:20:57+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-24T12:47:34+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-25T09:47:36+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-25T09:59:54+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-25T10:01:28+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T07:38:24+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T07:39:20+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T07:47:53+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T07:50:16+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T07:53:07+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T07:59:48+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T08:01:15+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T08:01:43+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T08:01:57+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T08:02:03+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T08:10:38+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T08:11:14+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T08:12:22+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T08:13:51+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T09:16:40+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-09-26T09:19:39+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-10-06T10:53:40+00:00 ERR (3): 
exception 'Mage_Customer_Exception' with message 'Customer email is required' in /var/www/magento/app/Mage.php:580
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Customer/Model/Resource/Customer.php(76): Mage::exception('Mage_Customer', 'Customer email ...')
#1 /var/www/magento/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1122): Mage_Customer_Model_Resource_Customer->_beforeSave(Object(Mage_Customer_Model_Customer))
#2 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Customer_Model_Customer))
#3 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#4 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/magento/index.php(87): Mage::run('', 'store')
#10 {main}
2014-10-06T10:53:57+00:00 ERR (3): 
exception 'Exception' with message 'Disallowed file type.' in /var/www/magento/lib/Varien/File/Uploader.php:254
Stack trace:
#0 /var/www/magento/lib/Varien/File/Uploader.php(180): Varien_File_Uploader->_validateFile()
#1 /var/www/magento/app/code/community/SSTech/Profileimage/Model/Profileimage.php(47): Varien_File_Uploader->save('/var/www/magent...', 'images.jpeg')
#2 /var/www/magento/app/code/community/SSTech/Profileimage/Model/Observer.php(11): SSTech_Profileimage_Model_Profileimage->saveProfileimageFile()
#3 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1338): SSTech_Profileimage_Model_Observer->saveCustomerProfileimage(Object(Varien_Event_Observer))
#4 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(SSTech_Profileimage_Model_Observer), 'saveCustomerPro...', Object(Varien_Event_Observer))
#5 /var/www/magento/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('customer_save_b...', Array)
#6 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('customer_save_b...', Array)
#7 /var/www/magento/app/code/core/Mage/Customer/Model/Customer.php(208): Mage_Core_Model_Abstract->_beforeSave()
#8 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(316): Mage_Customer_Model_Customer->_beforeSave()
#9 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#12 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#14 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 /var/www/magento/index.php(87): Mage::run('', 'store')
#16 {main}
2014-10-06T10:53:57+00:00 ERR (3): 
exception 'Mage_Customer_Exception' with message 'Customer email is required' in /var/www/magento/app/Mage.php:580
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Customer/Model/Resource/Customer.php(76): Mage::exception('Mage_Customer', 'Customer email ...')
#1 /var/www/magento/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1122): Mage_Customer_Model_Resource_Customer->_beforeSave(Object(Mage_Customer_Model_Customer))
#2 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Customer_Model_Customer))
#3 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#4 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/magento/index.php(87): Mage::run('', 'store')
#10 {main}
2014-10-06T10:54:57+00:00 ERR (3): 
exception 'Exception' with message 'Disallowed file type.' in /var/www/magento/lib/Varien/File/Uploader.php:254
Stack trace:
#0 /var/www/magento/lib/Varien/File/Uploader.php(180): Varien_File_Uploader->_validateFile()
#1 /var/www/magento/app/code/community/SSTech/Profileimage/Model/Profileimage.php(47): Varien_File_Uploader->save('/var/www/magent...', 'images.jpeg')
#2 /var/www/magento/app/code/community/SSTech/Profileimage/Model/Observer.php(11): SSTech_Profileimage_Model_Profileimage->saveProfileimageFile()
#3 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1338): SSTech_Profileimage_Model_Observer->saveCustomerProfileimage(Object(Varien_Event_Observer))
#4 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(SSTech_Profileimage_Model_Observer), 'saveCustomerPro...', Object(Varien_Event_Observer))
#5 /var/www/magento/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('customer_save_b...', Array)
#6 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('customer_save_b...', Array)
#7 /var/www/magento/app/code/core/Mage/Customer/Model/Customer.php(208): Mage_Core_Model_Abstract->_beforeSave()
#8 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(316): Mage_Customer_Model_Customer->_beforeSave()
#9 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#12 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#14 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 /var/www/magento/index.php(87): Mage::run('', 'store')
#16 {main}
2014-10-06T10:55:08+00:00 ERR (3): 
exception 'Exception' with message 'Disallowed file type.' in /var/www/magento/lib/Varien/File/Uploader.php:254
Stack trace:
#0 /var/www/magento/lib/Varien/File/Uploader.php(180): Varien_File_Uploader->_validateFile()
#1 /var/www/magento/app/code/community/SSTech/Profileimage/Model/Profileimage.php(47): Varien_File_Uploader->save('/var/www/magent...', 'images.jpeg')
#2 /var/www/magento/app/code/community/SSTech/Profileimage/Model/Observer.php(11): SSTech_Profileimage_Model_Profileimage->saveProfileimageFile()
#3 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1338): SSTech_Profileimage_Model_Observer->saveCustomerProfileimage(Object(Varien_Event_Observer))
#4 /var/www/magento/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(SSTech_Profileimage_Model_Observer), 'saveCustomerPro...', Object(Varien_Event_Observer))
#5 /var/www/magento/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('customer_save_b...', Array)
#6 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('customer_save_b...', Array)
#7 /var/www/magento/app/code/core/Mage/Customer/Model/Customer.php(208): Mage_Core_Model_Abstract->_beforeSave()
#8 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(316): Mage_Customer_Model_Customer->_beforeSave()
#9 /var/www/magento/app/code/community/SSTech/Profileimage/controllers/CustomerController.php(30): Mage_Core_Model_Abstract->save()
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): SSTech_Profileimage_CustomerController->uploadAction()
#11 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('upload')
#12 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#14 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 /var/www/magento/index.php(87): Mage::run('', 'store')
#16 {main}
2014-10-06T10:55:16+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-10-06T10:59:56+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-10-07T05:23:19+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
2014-10-07T05:30:45+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Invalid block type: ' in /var/www/magento/app/Mage.php:595
Stack trace:
#0 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Invalid block t...')
#1 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('', Array)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('', 'customer_edit')
#3 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('', 'customer_edit')
#4 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#6 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#7 /var/www/magento/app/code/core/Mage/Customer/controllers/AccountController.php(857): Mage_Core_Controller_Varien_Action->loadLayout()
#8 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Customer_AccountController->editAction()
#9 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/www/magento/index.php(87): Mage::run('', 'store')
#14 {main}
