<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function() {
	imagepreview_currentimage = 1;
});
//]]>
</script>
<div id="imagepreview_container" style="display: none;">
	<div id="imagepreview_content">
		<img id="imagepreview_image"></img>
		<div id="imagepreview_navigator">
			<div id="imagepreview_navibutton_first" onclick="showPI(0);"></div>
			<div id="imagepreview_navibutton_previous" onclick="showPI(imagepreview_currentimage - 1);"></div>
			<div id="imagepreview_imagenums" >1 / 2</div>
			<div id="imagepreview_navibutton_next" onclick="showPI(imagepreview_currentimage + 1);"></div>
			<div id="imagepreview_navibutton_last" onclick="showPI(-1);"></div>
		</div>
		<div id="imagepreview_content_close"></div>
	</div>
	<div id="imagepreview_background"></div>
</div>
