  <div id="home-featured">
	<!-- <h2 class="subtitle"><?php echo $this->__('Featured Products') ?></h2> -->
<div class="block-title">
        <!-- <strong><span><?php echo $this->__('Recently Viewed Products') ?></span></strong> -->
        <h2 class="subtitle"><?php echo $this->__('Featured Products') ?></h2>
    </div>
	
<div class="container">
    
	<?php
		// some helpers
		$_helper = $this->helper('catalog/output');
		$storeId = Mage::app()->getStore()->getId();
		$catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);
 
		// get all products that are marked as featured
		$collection = Mage::getModel('catalog/product')->getCollection();
		$collection->addAttributeToSelect('featured');
		$collection->addFieldToFilter(array(
			array('attribute' => 'featured', 'eq' => true),
		));
 
		// if no products are currently featured, display some text
		if (!$collection->count()) :
	?>
 
	<p class="note-msg"><?php echo $this->__('There are no featured products at the moment.') ?></p>
 
	<?php else : ?>
 
	<div class="category-products">
			<!-- <div class="row col-md-2"> -->
 
	<?php
		$_collectionSize = $collection->count();
		$_columnCount = 4;
		$i = 0;
 
		foreach ($collection as $_product) :
			$_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());
 
	?>
 
	    <?php if ($i++%$_columnCount==0): ?>
	    <?php endif ?>
	    <div class="row col-md-2">
	        <div class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
	           <div class="a-center">     
	            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
	            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">

                <?php
        // define the maximum length of the product name here
        
        echo Mage::helper('core/string')->truncate($this->escapeHtml($_product->getName()), $length = 20, $etc = '...', $remainder = '', $breakWords = true);
    ?>
	            </a>
	            </h2>
	            <?php if($_product->getRatingSummary()): ?>
	            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
	            <?php endif; ?>
	            <?php echo Mage::helper('core')->currency($_product->getPrice()); ?>
	            
	            <div class="actions">
	              <span class="row">
	                <?php if($_product->isSaleable()): ?>
	                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $catalog->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
	                <?php else: ?>
	                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
	                <?php endif; ?>
	              </span>
	                <!-- <div class="add-to-links">
	                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
	                        <div><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></div>
	                    <?php endif; ?>
	                    <?php if($_compareUrl=$catalog->getAddToCompareUrl($_product)): ?>
	                        <div><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></div>
	                    <?php endif; ?>
	                </div> -->
	            </div>
	            </div>
	        </div>
	    </div>
	    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
	    <?php endif ?>
		<?php endforeach ?>
        <!-- </div> -->
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
	</div>
	<?php endif ?>
  </div>
</div>