<!-- <h2 class="subtitle"><?php echo $this->__('Most Viewed Products') ?></h2> -->
<div class="block-title">
        <!-- <strong><span><?php echo $this->__('Recently Viewed Products') ?></span></strong> -->
        <h2 class="subtitle"><?php echo $this->__('Most Viewed Products') ?></h2>
    </div>

<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="container"> 
        <div class="products-grid products-grid--max-<?php $_collectionSize = 5;//count($_products->getItems()); echo $_collectionSize; ?>-col" id="products-grid-table">
            <?php $i=1; foreach ($_products->getItems() as $_product): ?>
                
                <div id="td_<?php echo $i;?>" <?php if($i%5==0 or $i==$_collectionSize){echo 'class="last"';} ?> >
                    <div id="cont_<?php echo $i;?>">
                        <div class=" row col-md-2">
                           <div >     
                                <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                                </a><div class="a-center" class="product-info" >
                                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                                 
                                 <?php
        // define the maximum length of the product name here
        
        echo Mage::helper('core/string')->truncate($this->escapeHtml($_product->getName()), $length = 22, $etc = '...', $remainder = '', $breakWords = true);
    ?>
                                </a>
                                </h3>
                                
                                <?php if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                			    <?php endif; ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <span class="row" >
                                <?php if($_product->isSaleable()): ?>
                                    <button class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><span><?php echo $this->__('Add to Cart') ?></span></span></span></button>
                                    <div class="clear"></div>
                                <?php else: ?>
                                    <p class="availability"><span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span></p>
                                    <div class="clear"></div>
                                <?php endif; ?></span></div>
                                <!-- <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li class="last"><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul> -->
                            </div>
                        </div>
                    </div>
                </div>
            <?php $i++; endforeach; $kol = $_collectionSize; ?>
        </div>
    </div>
<?php endif; ?>